import Config

config :sign_dict, :environment, :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :sign_dict, SignDictWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :sign_dict, :upload_path, "/var/signdict/uploads"

config :phoenix, :serve_endpoints, true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
